watch_stylesheet: true
watch_config: true
debug: false

komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"

bars:
  status-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 2
      left: 2
      bottom: 4
      right: 2
    widgets:
      left:
        [
          "volume",
          "media",
          "bluetooth",
          "cpu",
          "memory"
          
        ]
      center: [
         "active_window"
        ]
      right:
        [
          "weather",
          "traffic",
          "language",
          "notifications",
          "clock",
          "power_menu"
        ]
widgets:
  media:
      type: "yasb.media.MediaWidget"
      options:
        label: "<span>\uf001</span> {artist} - {title}"
        label_alt: "<span>\uf001</span> "
        show_thumbnail: false
        controls_only: false
        controls_left: false
        controls_hide: false
        hide_empty: true
        thumbnail_alpha: 80
        thumbnail_padding: 0
        thumbnail_corner_radius: 0
        callbacks:
          on_left: "toggle_media_menu"
        max_field_size:
          label: 38
          label_alt: 38
        scrolling_label:
          enabled: false
          update_interval_ms: 32
          style: "bounce-ease"  # can be "left", "right", "bounce", "bounce-ease"
          separator: " | "
          label_padding: 0
          # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
          ease_slope: 20
          ease_pos: 0.8
          ease_min: 0.5
        icons:
          prev_track: "\uf048"
          next_track: "\uf051"
          play: "\uf04b"
          pause: "\uf04c"
        media_menu:
          blur: false
          round_corners: false
          alignment: "right"
          direction: "down"
          offset_top: 6
          offset_left: 0
          thumbnail_corner_radius: 0
          thumbnail_size: 120
          max_title_size: 80
          max_artist_size: 20
          show_source: true
        media_menu_icons:
          prev_track: "\uf048"
          next_track: "\uf051"
          play: "\uf04b"
          pause: "\uf04c"
  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "<span>\uf4ab</span> {%H:%M}"
        label_alt: "<span>\uf4ab</span> {%A, %d %B %Y %H:%M}"
        timezones: [] #Looking up time zone info from registry
  komorebi_workspaces:
      type: "komorebi.workspaces.WorkspaceWidget"
      options:
          label_offline: "Komorebi Offline"
          label_workspace_btn: "\udb85\udcfc"
          label_workspace_active_btn: "\udb85\udcfb"
          label_default_name: "{index}"
          label_zero_index: false
          hide_empty_workspaces: false
          hide_if_offline: true
  komorebi_active_layout:
      type: "komorebi.active_layout.ActiveLayoutWidget"
      options:
        hide_if_offline: true
        label: "{icon}"
        layouts: ['bsp', 'columns', 'rows', 'grid', 'vertical_stack', 'horizontal_stack', 'ultrawide_vertical_stack','right_main_vertical_stack']
        layout_icons:
          bsp: "BSP"
          columns: "COLS"
          rows: "ROWS"
          grid: "GRID"
          vertical_stack: "V-STACK"
          horizontal_stack: "H-STACK"
          ultrawide_vertical_stack: "W-STACK"
          right_main_vertical_stack: "RMV-STACK"
          monocle: "MONOCLE"
          maximised: "MAX"
          floating: "FLOATING"
          paused: "PAUSED"
        callbacks:
          on_left: 'next_layout'
          on_middle: 'toggle_monocle'
          on_right: 'prev_layout'
  weather:
      type: "yasb.weather.WeatherWidget"
      options:
        label: "<span>{icon}</span> {conditions} {temp}"
        label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
        api_key: '3bf4cf9a7c3f40d6b31174128242807'
        update_interval: 600 #Update interval in seconds, Min 600
        hide_decimal: true
        location: 'Sofia'
        callbacks:
          on_left: "toggle_card"
        icons: 
          sunnyDay: "\ue30d"
          clearNight: "\ue32b"
          cloudyDay: "\udb81\udd99"
          cloudyNight: "\ue311"
          rainyDay: "\udb81\ude7e"
          rainyNight: "\udb81\ude7e"
          snowyDay: "\udb81\udd98"
          snowyNight: "\udb81\udd98"
          blizzardDay: "\uebaa"
          default: "\uebaa"
          # https://www.weatherapi.com/docs/
          # Usage {temp}, {min_temp}, {max_temp}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}
        weather_card:
          alignment: "right"
          direction: "down"
          icon_size: 64
          show_hourly_forecast: True # Set to False to disable hourly forecast
          time_format: "24h" # can be 12h or 24h
          hourly_point_spacing: 76
          hourly_icon_size: 32 # better to set 16, 32 or 64 for better quality
          icon_smoothing: true # should be true for smoother icon or false for sharper icon if using 16, 32 or 64 for hourly_icon_size
          temp_line_width: 2 # can be 0 to hide the temperature line
          current_line_color: "#8EAEE8"
          current_line_width: 1 # can be 0 to hide the current hour line
          current_line_style: "dot"
  volume:
      type: "yasb.volume.VolumeWidget"
      options:
        label: "<span>{icon}</span> {level}"
        label_alt: "{volume}"
        volume_icons:
          - "\ueee8"  # Icon for muted
          - "\uf026"  # Icon for 0-10% volume
          - "\uf027"  # Icon for 11-30% volume
          - "\uf027"  # Icon for 31-60% volume
          - "\uf028"  # Icon for 61-100% volume
        callbacks:
          on_right: "exec cmd.exe /c start ms-settings:sound"
  power_menu:
      type: "yasb.power_menu.PowerMenuWidget"
      options:
        label: "\uf011"
        uptime: True
        blur: False
        blur_background: True
        animation_duration: 250 # Milisecond 
        button_row: 5 # Number of buttons in row, min 1 max 5
        buttons:
          signout: ["\udb80\udf43","Sign out"]
          shutdown: ["\uf011","Shut Down"]
          restart: ["\uead2","Restart"]
          hibernate: ["\uf28e","Hibernate"]
          cancel: ["\udb81\udf3a","Cancel"]
  custom_button:
      type: "yasb.custom.CustomWidget"
      options:
        label: "<span>\ue22e</span>"
        label_alt: "<span>\uf40e</span>"
        class_name: "start-menu"
        callbacks:
          on_left: "exec start_menu"
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 200
      max_length_ellipsis: "..."
      monitor_exclusive: true
  bluetooth:
    type: "yasb.bluetooth.BluetoothWidget"
    options:
      label: "<span>{icon}</span> {device_count}"
      label_alt: "{device_name}"
      label_no_device: "No devices connected"
      label_device_separator: ", "
      max_length: 10
      max_length_ellipsis: "..."
      icons: 
        bluetooth_on: "\udb80\udcaf"
        bluetooth_off: "\udb80\udcb2"
        bluetooth_connected: "\udb80\udcb1"
      device_aliases:
        - name: "T5.0"
          alias: "\uf025"
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:bluetooth"
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "\ueb01 \ueab4 {download_speed} | \ueab7 {upload_speed}"
      label_alt: "Download {download_speed} | Upload {upload_speed}"
      update_interval: 1000
      menu:
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
      callbacks:
        on_left: "toggle_menu"
        on_right: "toggle_label"
  language:
    type: "yasb.language.LanguageWidget"
    options:
      label: "\uf11c {lang[country_code]}"
      label_alt: "{lang[full_name]}"
      update_interval: 5
      callbacks:
        on_left: "toggle_menu"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      language_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        show_layout_icon: true
        layout_icon: "\uf11c"
  pomodoro:
    type: "yasb.pomodoro.PomodoroWidget"
    options:
      label: "<span>{icon}</span> {remaining}"
      label_alt: "<span>{icon}</span> {session}/{total_sessions} - {status}"
      work_duration: 25
      break_duration: 5
      long_break_duration: 15
      long_break_interval: 4
      auto_start_breaks: true
      auto_start_work: true
      sound_notification: true
      show_notification: true
      hide_on_break: false
      session_target: 8
      icons:
        work: "\uf252"
        break: "\uf253"
        paused: "\uf254"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
      menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        circle_background_color: "#09ffffff"
        circle_work_progress_color: "#88c0d0"
        circle_break_progress_color: "#a3be8c"
        circle_thickness: 8
        circle_size: 160
      callbacks:
        on_left: "toggle_menu"
        on_middle: "reset_timer"
        on_right: "toggle_label"
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      min_bar_height: 0
      gradient: 1
      reverse: 1
      foreground: "#89b4fa"
      gradient_color_1: '#74c7ec'
      gradient_color_2: '#89b4fa'
      gradient_color_3: '#cba6f7'
      bars_number: 8
      bar_spacing: 2
      bar_width: 4
      hide_empty: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> CPU:{info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      cpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_free}"
      label_alt: "<span>\uefc5</span> VIRT: {virtual_mem_percent}% SWAP: {swap_mem_percent}%"
      update_interval: 1000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: false
      callbacks:
        on_left: "toggle_notification"
        on_right: "do_nothing"
        on_middle: "toggle_label"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
