watch_stylesheet: true
watch_config: true
debug: false
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: true
      round_corners_type: "small"
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 26
    padding:
      top: 2 # 4 4 2 4
      left: 4
      bottom: 2
      right: 4
    widgets:
      left:
        [
          "home",
          "active_window",
          "media",
          "cava"
        ]
      center:
        [
          "clock",
          "weather",
          "ai_chat"
        ]
      right:
        [
          "traffic",
          #"wifi",
          "sysinfo_widgets",
          "volume",
          "microphone",
          "wallpapers",
          "github",
          "notifications",
          "update",
          "power_menu"
        ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb85\uddfc</span>"
      menu_list:
      - { title: "Home", path: "~" }
      - { title: "Downloads", path: "$env:USERPROFILE/Downloads"}
      - { title: "Documents", path: "$env:USERPROFILE/Documents"}
      - { title: "Pictures", path: "E:/OneDrive/Pictures"} #Change to your Pictures Folder
      - { title: "Videos", path: "$env:USERPROFILE/Videos"}
      system_menu: true
      power_menu: false
      blur: true
      round_corners: true
      round_corners_type: "small"
      border_color: "system"
      distance: 5
      alignment: "left"
      direction: "down"
      menu_labels:
        shutdown: "Shutdown"
        restart: "Restart"
        logout: "Logout"
        lock: "Lock"
        sleep: "Sleep"
        system: "System Settings"
        about: "About This PC"
        task_manager: "Task Manager"
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 40
      max_length_ellipsis: "..."
      monitor_exclusive: true
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "<span>\udb80\udf87</span> {title}"
      label_alt: "<span>\udb80\udf87</span> {title}"
      hide_empty: true
      callbacks:
       on_left: "toggle_media_menu"
       on_middle: "do_nothing"
       on_right: "toggle_label"
      max_field_size:
        label: 40
        label_alt: 80
      show_thumbnail: true
      controls_only: false
      controls_left: true
      thumbnail_alpha: 80
      thumbnail_padding: 0
      thumbnail_corner_radius: 8
      thumbnail_edge_fade: true
      scrolling_label:
        enabled: false
        update_interval_ms: 100
        style: "left"  # can be "left", "right", "bounce", "bounce-ease"
        separator: " | "
        label_padding: 0
        # Easing curve params: https://www.desmos.com/calculator/j7eamemxzi
        ease_slope: 20
        ease_pos: 0.8
        ease_min: 0.5
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "system"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 4
        thumbnail_size: 80
        max_title_size: 80
        max_artist_size: 20
        show_source: true
        show_volume_slider: true
      media_menu_icons:
        play: "\uf04b"
        pause: "\uf04c"
        prev_track: "\uf048"
        next_track: "\uf051"
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      min_bar_height: 1
      noise_reduction: 0.77
      gradient: 1
      reverse: 1
      waveform: 0
      foreground: "#fac389"
      gradient_color_1: "#E6C13C"
      gradient_color_2: "#E66C3C"
      gradient_color_3: "#E63C60"
      bars_number: 20
      bar_spacing: 1
      bar_width: 2
      hide_empty: true
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b - %H:%M}"
      label_alt: "{%A, %d %B %Y - %H:%M}"
      timezones: []
      update_interval: 1000
      calendar:
        alignment: "center"
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "System"
        direction: "down"
        show_holidays: true
        show_week_numbers: False
        holiday_color: "#ff9f00"
      callbacks:
        on_left: "toggle_calendar"
        on_middle: "do_nothing"
        on_right: "toggle_label"
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label_alt: "<span>{icon}</span> {temp}" #  - {location}
      label: "<span>{icon}</span> {location} - {conditions}, {temp}" # Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "PASTE YOUR KEY HERE" # Get your free API key from https://www.weatherapi.com/
      update_interval: 300
      hide_decimal: true
      location: "Adelaide" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      units: "metric" # Can be 'metric' or 'imperial'
      callbacks:
        on_left: "toggle_card"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\ue3c2"
        cloudyDay: "\ue21d"
        cloudyNight: "\ue226"
        rainyDay: "\ue371"
        rainyNight: "\ue371"
        snowyDay: "\udb81\udf17"
        snowyNight: "\udb81\udf17"
        blizzardDay: "\udb81\udd99"
        default: "\udb81\udd99"
      weather_card:
        show_hourly_forecast: true
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        icon_size: 48
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  ai_chat:
    type: "yasb.ai_chat.AiChatWidget"
    options:
      label: "<span>\uf0e6</span>"
      chat:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_left: 0
        offset_top: 6
      icons:
        send: "\uf1d8"
        stop: "\uf04d"
        clear: "\uf1f8"
        assistant: "\udb81\ude74"
      notification_dot:
        enabled: false
        corner: "top_right"
        color: "red"
        margin: [ 0, 2 ]
      callbacks:
        on_left: "toggle_chat"
      providers:
        - provider: "OpenAI"
          api_endpoint: "https://api.openai.com/v1"
          credential: "PASTE YOUR KEY HERE" # Get your free key after logging in from https://platform.openai.com/api-keys
          models:
          - name: "gpt-4o-mini"
            label: "Chat GPT4"
            temperature: 0.3
            top_p: 0.95
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "\uf103  {download_speed}  |  {upload_speed}  \uf102"
      label_alt: "<span>\udb82\udcfa</span> Download {download_speed} | Upload {upload_speed}"
      update_interval: 1000
      speed_unit: "bytes"
      menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "system"
        alignment: "left"
        direction: "down"
        offset_top: 6
        offset_left: 0
      callbacks:
        on_left: "toggle_menu"
        on_right: "exec cmd.exe /c start ms-settings:network"
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  wifi:
    type: "yasb.wifi.WifiWidget"
    options:
      label: "\ueb01"
      label_alt: "{wifi_name} {wifi_strength}%"
      update_interval: 5000
      callbacks:
        on_left: "exec quick_settings"
        on_middle: "toggle_label"
        on_right: "exec cmd.exe /c start ms-settings:network"
      ethernet_label: "\ueb01"
      ethernet_label_alt: "\ueb01 {ip_addr}"
      ethernet_icon: "\ueba9"
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\uf09b</span>"
      label_alt: "{data} Notifications" # {data} return number of unread notification
      token: PASTE YOUR TOKEN HERE # GitHub Personal access tokens (classic) https://github.com/settings/tokens
      max_notification: 20 # Max number of notification displaying in menu max: 50
      notification_dot:
        enabled: True
        corner: "bottom_right" # Can be "top_left", "top_right", "bottom_left", "bottom_right"
        color: "#FF534D" # Can be hex color or string - Set same as red variable in stylesheet
        margin: [ 1, 4 ] # x and y margin for the dot
      only_unread: false # Show only unread or all notifications; 
      max_field_size: 54 # Max characters in title before truncation.
      update_interval: 300 # Check for new notification in seconds
      menu:
        blur: True # Enable blur effect for the menu
        round_corners: True # Enable round corners for the menu (this option is not supported on Windows 10)
        round_corners_type: "small" # Set the type of round corners for the menu (normal, small) (this option is not supported on Windows 10)
        border_color: "System" # Set the border color for the menu (this option is not supported on Windows 10)
        alignment: "right"
        direction: "down"
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      update_interval: 2000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  gpu:
    type: "yasb.gpu.GpuWidget"
    options:
      label: "<span>\ue266</span>{info[utilization]}% | {info[temp]}°C"
      label_alt: "<span>\ue266</span>{info[mem_used]} | {info[temp]}°C"
      update_interval: 2000
      gpu_thresholds:
        low: 25
        medium: 50
        high: 90
      histogram_icons:
        - "\u2581" # 0%
        - "\u2581" # 10%
        - "\u2582" # 20%
        - "\u2583" # 30%
        - "\u2584" # 40%
        - "\u2585" # 50%
        - "\u2586" # 60%
        - "\u2587" # 70%
        - "\u2588" # 80%+
      histogram_num_columns: 8
      callbacks:
        on_left: "toggle_label"
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span>\uf473</span>"
      label_alt: "<span>\uf473</span>"
      update_interval: 60
      group_label:
        volume_labels: ["C", "D", "E", "F"]
        show_label_name: false
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "System"
        alignment: "right"
        direction: "down"
      callbacks:
        on_left: "toggle_group"
        on_middle: "toggle_label"
        on_right: "exec explorer" # Open disk C in file explorer
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      audio_menu:
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 80
        show_apps: true # Whether to show the list of applications with audio sessions
        show_app_labels: true # Whether to show application labels in the audio menu
        show_app_icons: true # Whether to show application icons in the audio menu
        show_apps_expanded: true # Whether application volumes are expanded by default when opening the menu
        app_icons: # Icons for the toggle button to expand/collapse application volumes
          toggle_down: "\uf078" # Icon for btn collapsed state
          toggle_up: "\uf077" # Icon for btn expa
      callbacks:
        on_left: "toggle_volume_menu"
        on_middle: "exec cmd.exe /c start ms-settings:sound"
        on_right: "toggle_mute"
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  microphone:
    type: "yasb.microphone.MicrophoneWidget"
    options:
      label: "<span>{icon}</span>"
      label_alt: "<span>{icon}</span> {level}"
      icons:
        normal: "\uf130"
        muted: "\uf131"
      callbacks:
        on_left: "toggle_mic_menu"
        on_middle: "exec cmd.exe /c start ms-settings:sound"
        on_right: "toggle_mute"
      mic_menu:
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "System"
        alignment: "right"
        direction: "down"
        offset_top: 6
        offset_left: 0
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf00f</span>"
      image_path: "E:\\OneDrive\\Pictures\\Wallpaper" # Example path to folder with images
      change_automatically: false # Automatically change wallpaper
      update_interval: 1800 # If change_automatically is true, update interval in seconds
      gallery:
        enabled: true
        blur: true
        image_width: 220
        image_per_page: 6
        show_buttons: true
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: true
      run_after: # List of functions to run after wallpaper is updated
        #- "wal -s -t -e -q -n -i {image}" # Example command to run after wallpaper is updated
        #- "cmd.exe /c start /min pwsh ./yasb.ps1" # Example command to run after wallpaper is updated
      label_shadow:
        enabled: false
        color: "black"
        radius: 3
        offset: [ 1, 1 ]
  notifications:
    type: "yasb.notifications.NotificationsWidget"
    options:
      label: "<span>\uf476</span> {count}"
      label_alt: "{count} notifications"
      hide_empty: true
      tooltip: true
      callbacks:
        on_left: "toggle_notification"
        on_right: "toggle_label"
        on_middle: "do_nothing" 
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  update:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 30
        exclude: []
      windows_update:
        enabled: true
        label: "<span>\uf0ab</span>{count}"
        interval: 240
        exclude: []
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      uptime: True
      blur: False
      blur_background: True
      animation_duration: 250 # Milisecond 
      button_row: 5 # Number of buttons in row, min 1 max 5
      buttons:
        signout: ["\udb80\udf43","Sign out"]
        shutdown: ["\uf011","Shut Down"]
        restart: ["\uead2","Restart"]
        hibernate: ["\uf28e","Hibernate"]
        cancel: ["\udb81\udf3a","Cancel"]
      label_shadow:
        enabled: false
        color: "black"
        radius: 1
        offset: [ 1, 1 ]
  sysinfo_widgets:
    type: "yasb.grouper.GrouperWidget"
    options:
      class_name: "sysinfo-grouped-widgets"
      widgets: [
        "cpu",
        "memory",
        "gpu",
        "disk",
      ]
