watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"
bars:
  primary-bar:
    enabled: true
    screens: ['*']
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      always_on_top: true
      windows_app_bar: true
      hide_on_fullscreen: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 3
      left: -1
      bottom: 1
      right: 4
    widgets:
      left: [
        "komorebi_workspaces",
        "active_window"
      ]
      center: []
      right: [
        "systray",
        "traffic",
        "cpu",
        "volume",
        "clock",
        "media",
        "notifications"
      ]
widgets:
  komorebi_workspaces:
      type: "komorebi.workspaces.WorkspaceWidget"
      options:
        label_offline: "Komorebi OFFLINE"
        label_default_name: ""
        label_zero_index: false
        hide_empty_workspaces: true
        hide_if_offline: true
  active_window:
      type: "yasb.active_window.ActiveWindowWidget"
      options:
        label: "{win[title]}"
        label_alt: "{win[title]}"
        label_no_window: ""
        label_icon: false
        label_icon_size: 12
        max_length: 50
        max_length_ellipsis: "..."
        monitor_exclusive: false
  systray:
      type: "yasb.systray.SystrayWidget"
      options:
        class_name: "systray"
        show_unpinned: false
        show_unpinned_button: true
        show_battery: false
        show_volume: false
        show_network: false
  traffic:
      type: "yasb.traffic.TrafficWidget"
      options:
        label: "<span>\udb82\udcfa</span>"
        label_alt: "{download_speed} | \ueaa1 {upload_speed}"
        update_interval: 1000
        callbacks:
          on_left: 'toggle_label'
  cpu:
      type: "yasb.cpu.CpuWidget"
      options:
        label: "<span>\uf4bc</span> {info[percent][total]}%"
        label_alt: "{info[histograms][cpu_percent]}"
        update_interval: 1000
        histogram_icons:
          - '\u2581' # 0%
          - '\u2581' # 10%
          - '\u2582' # 20%
          - '\u2583' # 30%
          - '\u2584' # 40%
          - '\u2585' # 50%
          - '\u2586' # 60%
          - '\u2587' # 70%
          - '\u2588' # 80%+
        histogram_num_columns: 8
        callbacks:
          on_right: "exec cmd /c Taskmgr"
        container_padding:
          top: 0
          left: 12
          bottom: 0
          right: 0
  volume:
        type: "yasb.volume.VolumeWidget"
        options:
          label: "<span>{icon}</span> {level}"
          volume_icons:
            - "\ueee8"  # Icon for muted
            - "\uf026"  # Icon for 0-10% volume
            - "\uf027"  # Icon for 11-30% volume
            - "\uf027"  # Icon for 31-60% volume
            - "\uf028"  # Icon for 61-100% volume
  clock:
      type: "yasb.clock.ClockWidget"
      options:
        label: "{%I:%M %p}"
        label_alt: "{%A, %d %B %Y}"
        callbacks:
          on_left: "toggle_calendar"
          on_right: "toggle_label"
  media:
        type: "yasb.media.MediaWidget"
        options:
          label: "{title}"
          label_alt: "{artist}"
          max_field_size:
            label: 40
            label_alt: 40
          show_thumbnail: false
          controls_hide: false
          hide_empty: true
          thumbnail_alpha: 80
          thumbnail_padding: 0
          thumbnail_corner_radius: 0
          icons:
            prev_track: "\ue892"
            next_track: "\ue893"
            play: "\ue768"
            pause: "\ue769"
  notifications:
      type: "yasb.notifications.NotificationsWidget"
      options:
        label: "<span>\uf476</span> {count}"
        label_alt: "{count} notifications"
        hide_empty: true
        tooltip: false
        container_padding:
          top: 0
          left: 10
          bottom: 0
          right: 12
        callbacks:
          on_left: "toggle_notification"
          on_right: "toggle_label"
        label_shadow:
          enabled: false
          color: "black"
          radius: 3
          offset: [ 1, 1 ]
