watch_stylesheet: true
watch_config: true
debug: false
show_systray: true
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic stop --whkd && komorebic start --whkd"
bars:
  primary-bar:
    enabled: true
    screens: ["**"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      align: "center"
    animation:
      enabled: true
      duration: 1000
    blur_effect:
      enabled: false 
      acrylic: true 
      dark_mode: true
      round_corners: false
      border_color: None
    window_flags:
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 1
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: [
        "home",
        "komorebi_workspaces",
        "systray",
        "disk",
        "apps",
        "media",
        "volume"
      ]
      center: [
        "clock",
        "weather"
      ]
      right: [
        "active_window",
        "taskbar",
        "cpu",
        "memory",
        "wifi",
        "traffic",
        "power_menu"
      ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\udb81\udf17</span>"
      container_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      menu_list:
      - { title: "User Home", path: "~" }
      - { title: "Download", path: "~\\Downloads" }
      - { title: "Documents", path: "~\\Documents" }
      - { title: "Pictures", path: "~\\Pictures" }
      system_menu: true
      power_menu: true
      blur: true
      border_color: "None"
      round_corners_type: "small"
      container_padding:
        top: 0
        left: 12
        bottom: 0
        right: 12
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      container_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      label_shadow:
        enabled: true
        offset: [0, 0]
        radius: 4
        color: "#feed00"
      label_offline: "\u23fc Offline"
      label_workspace_btn: "\udb80\uddc6"
      label_workspace_active_btn: "\ue285  \ue200"
      label_workspace_populated_btn: "\uf00d"
      label_default_name: "{index}"
      label_zero_index: true
      hide_empty_workspaces: false
      hide_if_offline: false
      animation: true
      enable_scroll_switching: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
  systray:
    type: "yasb.systray.SystrayWidget"
    options:
      class_name: "systray"
      label_collapsed: "\udb81\udeb6"
      label_expanded: "\udb82\ude03"
      label_position: "left"
      container_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#46dffb"
      icon_size: 12 
      pin_click_modifier: "alt" 
      show_unpinned: false
      show_unpinned_button: true
      show_network: true
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "\ue240"
      label_alt: "{volume_label} {space[used][gb]} / {space[total][gb]}"
      label_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      update_interval: 60
      disk_thresholds:
        low: 25
        medium: 50
        high: 90
      animation:
        enabled: true
        type: "fadeInOut"
        duration: 1500
      group_label:
        volume_labels: ["C", "D", "E", "F"]
        show_label_name: true
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "System"
        alignment: "left"
        direction: "down"
        distance: 6
      progress_bar:
        enabled: true
        position: "left"
        size: 14
        thickness: 2
        color: "#ff00d4"
        animation: true
      callbacks:
        on_left: "toggle_group"
        on_middle: "toggle_label"
        on_right: "exec explorer"
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      image_icon_size: 14
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      label: "{data}"
      tooltip: True
      label_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      app_list:
        - { icon: "\uf422", launch: "~\\AppData\\Local\\Programs\\EverythingToolbar\\EverythingToolbar.Launcher.exe", name: "Search" }
        - { icon: "\ueb01", launch: "~\\Path\\To-Your\\Browser", name: "Network" }
        - { icon: "\uf1bc", launch: "~\\Path\\To-Your\\Spotify", name: "Spotify" }
        - { icon: "\uf1ff",launch: "~\\Path\\To-Your\\Discord", name: "Discord" }
        - { icon: "\udb82\ude1e",launch: "~\\Path\\To-Your\\VSCode", name: "VSCode" }
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{artist} - {title}"
      label_alt: "{title}"
      label_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 2
        color: "#00ffd2"
      container_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      max_field_size:
        label: 32
        label_alt: 32
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 150
      thumbnail_padding: 8
      thumbnail_corner_radius: 0
      icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
      media_menu_icons:
        prev_track: "\uf048"
        next_track: "\uf051"
        play: "\uf04b"
        pause: "\uf04c"
        mute: "\uf6a9"
        unmute: "\uf028"
      media_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "system"
        alignment: "center"
        direction: "down"
        offset_top: 6
        offset_left: 0
        thumbnail_corner_radius: 8
        thumbnail_size: 120
        max_title_size: 60
        max_artist_size: 20
        show_source: true
        show_volume_slider: true
      container_padding:
        top: 8
        left: 8
        bottom: 8
        right: 8
      scrolling_label:
        enabled: true
        always_scroll: false
        update_interval_ms: 16 
        style: "left" 
        separator: "    |    "
        label_padding: 1
      callbacks:
        on_left: "toggle_media_menu"
        on_middle: "focus_media"
        on_right: "toggle_label"
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      label_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      tooltip: true
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_left: "toggle_volume_menu"
        on_right: "toggle_mute"
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "None"
        alignment: "center"
        direction: "down"
        distance: 6
        show_apps: true
        show_apps_expanded: true
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 8
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "<span>\uf017</span> {%a, %d/%m/%y %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M}"
      label_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 3
        color: "#00ffd2"
      container_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 2
        color: "#ff003c"
      callbacks:
        on_left: "toggle_calendar"
        on_middle: "next_timezone"
        on_right: "toggle_label"
      calendar:
        blur: True
        round_corners: True
        round_corners_type: "small"
        border_color: "None"
        alignment: "center"
        direction: "down"
        distance: 6
        show_holidays: true
        country_code: "$env:YASB_CALENDAR_COUNTRY_CODE"
        subdivision: "$env:YASB_CALENDAR_SUBDIVISION"
        holiday_color: "#ff003c"
        extended: true
        show_week_numbers: true
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 0
      timezones: ["JP"]
      icons:
        clock_01 : "\udb85\udc3f"
        clock_02 : "\udb85\udc40"
        clock_03 : "\udb85\udc41"
        clock_04 : "\udb85\udc42"
        clock_05 : "\udb85\udc43"
        clock_06 : "\udb85\udc44"
        clock_07 : "\udb85\udc45"
        clock_08 : "\udb85\udc46"
        clock_09 : "\udb85\udc47"
        clock_10 : "\udb85\udc48"
        clock_11 : "\udb85\udc49"
        clock_12 : "\udb85\udc4a"
        clock_16 : "SNACK TIME !"
        clock_21 : "Zzz..."
        clock_22 : "Zzz..."
        clock_23 : "Zzz..."
      alarm_icons:
        enabled: "\uf0f3"
        disabled: "\uf0a2"
        snooze: "\uf1f6"
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      label_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 3
        color: "#00ffd2"
      container_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      api_key: "$env:YASB_WEATHER_API_KEY"
      show_alerts: true
      tooltip: true
      update_interval: 600
      hide_decimal: true
      units: "metric"
      location: "$env:YASB_WEATHER_LOCATION"
      callbacks:
        on_left: "toggle_card"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\U0001F319"
        cloudyDay: "\U00002601"
        cloudyNight: "\U0001F315"
        rainyDay: "\U0001F327"
        rainyNight: "\U0001F327\U0001F311"
        snowyDay: "\U00002744"
        snowyNight: "\U0001F328"
        blizzardDay: "\U0001F32C"
        blizzardNight: "\udb83\udf36"
        foggyDay: "\ue303"
        foggyNight: "\ue346"
        thunderstormDay: "\ue30f"
        thunderstormNight: "\ue338"
        default: "\udb81\udd99"
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 8
      weather_card: 
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "None"
        alignment: "center"
        direction: "down"
        distance: 6
        icon_size: 64
        show_hourly_forecast: true
        time_format: "24h"
        hourly_point_spacing: 76
        hourly_icon_size: 32
        icon_smoothing: true
        temp_line_width: 2
        current_line_color: "#00ffd2"
        current_line_width: 1
        current_line_style: "dot"
        hourly_gradient:
          enabled: true
          top_color: "#04d8044d"
          bottom_color: "#00000000"
        hourly_forecast_buttons:
          enabled: true
          default_view: "temperature"
          temperature_icon: "\udb81\udd99"
          rain_icon: "\udb81\udd96"
          snow_icon: "\udb81\udd98"
        weather_animation:
          enabled: true
          snow_overrides_rain: false
          temp_line_animation_style: "both"
          rain_effect_intensity: 1.0
          snow_effect_intensity: 1.0
          scale_with_chance: true
          enable_debug: false
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 12
      label_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 3
        color: "#00ffd2"
      container_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      max_length: 32
      max_length_ellipsis: "..."
      monitor_exclusive: true
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation:
        enabled: true
      icon_size: 14
      show_only_visible: false
      tooltip: true
      monitor_exclusive: true
      hide_empty: true
      label_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 3
        color: "#00ffd2"
      container_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      preview:
        enabled: true
        width: 240
        delay: 400
        padding: 8
        margin: 8
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
      callbacks:
        on_left: "toggle_window"
        on_middle: "do_nothing"
        on_right: "context_menu"
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span>\uf4bc</span> {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      label_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      update_interval: 2000
      histogram_icons:
        [
        "\u2581", # 0%
        "\u2581", # 10%
        "\u2582", # 20%
        "\u2583", # 30%
        "\u2584", # 40%
        "\u2585", # 50%
        "\u2586", # 60%
        "\u2587", # 70%
        "\u2588"  # 80%+
        ] 
      histogram_num_columns: 8
      callbacks:
        on_right: "toggle_label"
        on_left: "exec cmd /c Taskmgr"
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 0
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_used}/{virtual_mem_total}"
      label_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      update_interval: 5000
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      container_padding:
        top: 0
        left: 6
        bottom: 0
        right: 8
  wifi:
      type: "yasb.wifi.WifiWidget"
      options:
        label: "<span>{wifi_icon}</span>"
        label_alt: "{wifi_name} {wifi_strength}%"
        label_shadow:
          enabled: true
          offset: [-1, 2]
          radius: 1
          color: "#ff003c"
        update_interval: 5000
        callbacks:
          on_left: "toggle_menu"
          on_middle: "do_nothing"
          on_right: "exec cmd.exe /c start ms-settings:network`"
        animation:
          enabled: true
          type: "fadeInOut"
          duration: 1000
        menu_config:
          blur: true
          round_corners: true
          round_corners_type: "normal"
          border_color: "#46dffb"
          alignment: "center"
          direction: "down"
          offset_top: 0
          offset_left: 0
          wifi_icons_secured: [
            "\ue670",
            "\ue671",
            "\ue672",
            "\ue673",
          ]
          wifi_icons_unsecured: [
            "\uec3c",
            "\uec3d",
            "\uec3e",
            "\uec3f",
          ]
        container_padding:
          top: 0
          left: 8
          bottom: 0
          right: 8
        wifi_icons: [
          "\udb82\udd2e",  # Icon for 0% strength
          "\udb82\udd1f",  # Icon for 1-20% strength
          "\udb82\udd22",  # Icon for 21-40% strength
          "\udb82\udd25",  # Icon for 41-80% strength
          "\udb82\udd28"   # Icon for 81-100% strength
        ]
  traffic:
      type: "yasb.traffic.TrafficWidget"
      options:
        label: "<span>\uf0ab</span> {download_speed}   <span>\uf0aa</span> {upload_speed}"
        label_alt: "Today Down: {today_downloaded} | Today Up: {today_uploaded}"
        label_shadow:
          enabled: true
          offset: [-1, 2]
          radius: 1
          color: "#00ffd2"
        container_shadow:
          enabled: true
          offset: [-1, 2]
          radius: 1
          color: "#ff003c"
        update_interval: 1000
        max_label_length: 8
        max_label_length_align: "center"
        hide_decimal: true
        callbacks:
          on_left: "toggle_menu"
          on_middle: "do_nothing"
          on_right: "toggle_label"
        menu:
          blur: true
          round_corners: true
          round_corners_type: "small"
          border_color: None
          alignment: "right"
          direction: "down"
        animation:
          enabled: true
          type: "fadeInOut"
          duration: 600
        container_padding:
          top: 0
          left: 0
          bottom: 0
          right: 8 
  power_menu:
    type: "yasb.power_menu.PowerMenuWidget"
    options:
      label: "\uf011"
      label_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#00ffd2"
      container_shadow:
        enabled: true
        offset: [-1, 2]
        radius: 1
        color: "#ff003c"
      uptime: True
      blur: True
      blur_background: True
      animation_duration: 200
      button_row: 4
      buttons:
        shutdown: ["\udb81\ude8c", "Shut Down"]
        restart: ["\ue00a", "Restart"]
        signout: ["\ue009", "Sign out"]
        sleep: ["\udb81\udcb2", "Sleep"]
        cancel: ["", "Cancel"]
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
